---
title: "ReadMe"
author: "Koen Spoorenberg"
date: "12 August 2016"
output: word_document
---
Glossery:

This was built as part of a deliverable for the course Developing Data Products as part of the Coursera Data Science Specialization.
- The app demonstrates the 'Race time prediction' algoritm developed by Peter Riegel. An algoritm which predicts running times based on races over different distances.
- There are more algoritms available(for example the VO2 max prediction/Cameron formula/Purdy formula). These algoritms are more difficult and do not seem to over a much better prediction.
- The app developed for the first part of the assignment demo is avalilable at: https://kspoorenberg.shinyapps.io/Racetime_prediction_in_running/
- Source code for ui.R and server.R files are available on the GitHub repo:https://github.com/KoenSpoorenberg/RaceTimePrediction

How to use the app:

Change one of the parameters in the left pane and press submit. 
Results will be displayed in the right pane.


